In [1]:
import numpy as np

In [9]:
A = [[8, 1, 6], [3, 5, 7], [4, 9, 2]]
evals, evecs = np.linalg.eig(A)

In [4]:
print(evals)
print(evecs)

[ 15.           4.89897949  -4.89897949]
[[-0.57735027 -0.81305253 -0.34164801]
 [-0.57735027  0.47140452 -0.47140452]
 [-0.57735027  0.34164801  0.81305253]]


In [5]:
equationA = [1, -15, -24, 360]
evals = np.roots(equationA)
print('特征值：', evals)

特征值： [ 15.          -4.89897949   4.89897949]


In [10]:
sigma = evals * np.eye(3)
print(sigma)

[[ 15.           0.          -0.        ]
 [  0.           4.89897949  -0.        ]
 [  0.           0.          -4.89897949]]


In [11]:
print(evecs * sigma * np.linalg.inv(evecs))

[[ 5.          0.         -0.        ]
 [ 0.          1.63299316  0.        ]
 [ 0.         -0.         -3.13299316]]
